parameters:
  maco.open_ai_translator.job: 'update_product_translations'
services:
  Macopedia\OpenAiTranslator\Connector\Processor\MassEdit\TranslateAttributesProcessor:
    arguments:
      - '@Macopedia\OpenAiTranslator\Service\TranslateAttributesService'

  macopedia.job.update_product_translations:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - '%maco.open_ai_translator.job%'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      -
          - '@macopedia.step.validate_openai_key_tasklet'
          - '@macopedia.step.update_product_translations.mass_edit'
    tags:
      - { name: akeneo_batch.job, connector: 'Macopedia OpenAi Connector', type: '%pim_enrich.job.mass_edit_type%' }

  macopedia.job.default_values_provider.translate_product:
    class: Macopedia\OpenAiTranslator\Connector\Job\JobParameters\DefaultValueProvider\TranslateAttributes
    arguments:
      - [ '%maco.open_ai_translator.job%' ]
      - '%open_ai_key%'
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }

  macopedia.job.constraint_collection_provider.translate_product:
    class: Macopedia\OpenAiTranslator\Connector\Job\JobParameters\ConstraintCollectionProvider\TranslateAttributes
    arguments:
      - [ '%maco.open_ai_translator.job%' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

  macopedia.step.update_product_translations.mass_edit:
    class: '%pim_connector.step.item_step.class%'
    arguments:
      - 'translate'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_enrich.reader.database.product_and_product_model'
      - '@Macopedia\OpenAiTranslator\Connector\Processor\MassEdit\TranslateAttributesProcessor'
      - '@pim_enrich.writer.database.product_and_product_model_writer'
      - '%pim_job_product_batch_size%'

  Macopedia\OpenAiTranslator\Connector\Tasklet\ValidateOpenAiKeyTasklet: ~

  macopedia.step.validate_openai_key_tasklet:
    class: '%pim_connector.step.tasklet.class%'
    arguments:
      - 'validate_openai_key'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@Macopedia\OpenAiTranslator\Connector\Tasklet\ValidateOpenAiKeyTasklet'