services:
  Macopedia\OpenAiTranslator\Repository\AttributeRepository:
    factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
    arguments: [ '%pim_catalog.entity.attribute.class%' ]
    tags:
      - { name: 'pim_repository' }
