parameters:
  open_ai_key: '%env(default::OPEN_AI_KEY)%'
services:
  Macopedia\OpenAiTranslator\Client\OpenAiClient:
    arguments:
      - 'gpt-3.5-turbo'
      - '%open_ai_key%'

  Macopedia\OpenAiTranslator\Translator\OpenAiTranslator:
    arguments:
      - '@Macopedia\OpenAiTranslator\Client\OpenAiClient'

  Macopedia\OpenAiTranslator\Service\TranslateAttributesService:
    arguments:
      - '@Macopedia\OpenAiTranslator\Translator\OpenAiTranslator'
      - '@Macopedia\OpenAiTranslator\Repository\AttributeRepository'
      - '@pim_catalog.entity_with_family_variant.check_attribute_editable'
      - '@pim_catalog.updater.property_setter'
      - '@logger'
