services:
  Macopedia\Translator\Client\OpenAiClient:
    arguments:
      - '@logger'
      - 'gpt-3.5-turbo'
      - '%env(OPEN_AI_KEY)%'

  Macopedia\Translator\Translator\OpenAiTranslator:
    arguments:
      - '@Macopedia\Translator\Client\OpenAiClient'

  Macopedia\Translator\Service\TranslateAttributesService:
    arguments:
      - '@Macopedia\Translator\Translator\OpenAiTranslator'
      - '@pim_catalog.repository.attribute'
      - '@pim_catalog.entity_with_family_variant.check_attribute_editable'
      - '@pim_catalog.updater.property_setter'
