services:
  Macopedia\Translator\Connector\Processor\MassEdit\TranslateAttributesProcessor:
    arguments:
      - '@Macopedia\Translator\Translator\OpenAiTranslator'
      - '@pim_catalog.repository.attribute'
      - '@pim_catalog.entity_with_family_variant.check_attribute_editable'
      - '@pim_catalog.updater.property_setter'

 # Google\Cloud\Translate\V2\TranslateClient:
  #  arguments:
   #   - { key: '%env(GOOGLE_API_KEY)%' }

  macopedia.job.update_product_translations:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - 'update_product_translations'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - [ '@macopedia.step.update_product_translations.mass_edit' ]
    tags:
      - { name: akeneo_batch.job, connector: '%pim_enrich.connector_name.mass_edit%', type: '%pim_enrich.job.mass_edit_type%' }

  macopedia.job.default_values_provider.translate_product:
    class: Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\DefaultValueProvider\ProductMassEdit
    arguments:
      - [ 'update_product_translations' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }

  macopedia.job.constraint_collection_provider.translate_product:
    class: 'Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductMassEdit'
    arguments:
      - [ 'update_product_translations' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

  macopedia.step.update_product_translations.mass_edit:
    class: '%pim_connector.step.item_step.class%'
    arguments:
      - 'perform'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_enrich.reader.database.product_and_product_model'
      - '@Macopedia\Translator\Connector\Processor\MassEdit\TranslateAttributesProcessor'
      - '@pim_enrich.writer.database.product_and_product_model_writer'
      - '%pim_job_product_batch_size%'

  Macopedia\Translator\Client\OpenAiClient:
    arguments:
      - '@logger'
      - 'gpt-3.5-turbo'
      - '%env(OPEN_AI_KEY)%'

  Macopedia\Translator\Translator\OpenAiTranslator:
    arguments:
      - '@Macopedia\Translator\Client\OpenAiClient'
